require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SetUsersController do

  # This should return the minimal set of attributes required to create a valid
  # SetUser. As you add validations to SetUser, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all set_users as @set_users" do
      set_user = SetUser.create! valid_attributes
      get :index
      assigns(:set_users).should eq([set_user])
    end
  end

  describe "GET show" do
    it "assigns the requested set_user as @set_user" do
      set_user = SetUser.create! valid_attributes
      get :show, :id => set_user.id.to_s
      assigns(:set_user).should eq(set_user)
    end
  end

  describe "GET new" do
    it "assigns a new set_user as @set_user" do
      get :new
      assigns(:set_user).should be_a_new(SetUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested set_user as @set_user" do
      set_user = SetUser.create! valid_attributes
      get :edit, :id => set_user.id.to_s
      assigns(:set_user).should eq(set_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SetUser" do
        expect {
          post :create, :set_user => valid_attributes
        }.to change(SetUser, :count).by(1)
      end

      it "assigns a newly created set_user as @set_user" do
        post :create, :set_user => valid_attributes
        assigns(:set_user).should be_a(SetUser)
        assigns(:set_user).should be_persisted
      end

      it "redirects to the created set_user" do
        post :create, :set_user => valid_attributes
        response.should redirect_to(SetUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved set_user as @set_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        SetUser.any_instance.stub(:save).and_return(false)
        post :create, :set_user => {}
        assigns(:set_user).should be_a_new(SetUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SetUser.any_instance.stub(:save).and_return(false)
        post :create, :set_user => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested set_user" do
        set_user = SetUser.create! valid_attributes
        # Assuming there are no other set_users in the database, this
        # specifies that the SetUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SetUser.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => set_user.id, :set_user => {'these' => 'params'}
      end

      it "assigns the requested set_user as @set_user" do
        set_user = SetUser.create! valid_attributes
        put :update, :id => set_user.id, :set_user => valid_attributes
        assigns(:set_user).should eq(set_user)
      end

      it "redirects to the set_user" do
        set_user = SetUser.create! valid_attributes
        put :update, :id => set_user.id, :set_user => valid_attributes
        response.should redirect_to(set_user)
      end
    end

    describe "with invalid params" do
      it "assigns the set_user as @set_user" do
        set_user = SetUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SetUser.any_instance.stub(:save).and_return(false)
        put :update, :id => set_user.id.to_s, :set_user => {}
        assigns(:set_user).should eq(set_user)
      end

      it "re-renders the 'edit' template" do
        set_user = SetUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SetUser.any_instance.stub(:save).and_return(false)
        put :update, :id => set_user.id.to_s, :set_user => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested set_user" do
      set_user = SetUser.create! valid_attributes
      expect {
        delete :destroy, :id => set_user.id.to_s
      }.to change(SetUser, :count).by(-1)
    end

    it "redirects to the set_users list" do
      set_user = SetUser.create! valid_attributes
      delete :destroy, :id => set_user.id.to_s
      response.should redirect_to(set_users_url)
    end
  end

end
